spring.application.name=Turf
spring.datasource.url=jdbc:mysql://localhost:3306/turf_management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Chinnu@2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=/5Clg6c+A28XwASB7djb7QtRYez2brqdrDZb5onICA0cLXkl5rs03Ux5s3lkbgazyXShQnze4WSy9mHJpWcdUg==
app.jwt.expiration-ms=86400000

logging.level.org.springframework.security=DEBUG
server.port=8080